# tests/phase3_gate.py
#
# PHASE 3 GATE — Professor Agent
# Requirement: Top 40% on Spaceship Titanic public leaderboard.
#
# This file does three things:
#   1. Runs the full Professor pipeline on Spaceship Titanic train data
#   2. Submits the resulting submission.csv to Kaggle via the API
#   3. Polls the public leaderboard and asserts a top-40% finish
#
# Run with:
#   python tests/phase3_gate.py
#
# Prerequisites:
#   KAGGLE_USERNAME and KAGGLE_KEY in .env
#   Professor pipeline fully built (Days 1-19)
#   Spaceship Titanic competition rules accepted at kaggle.com
#
# If this gate FAILS:
#   Do NOT proceed to Phase 4.
#   Do NOT edit this file to make it pass.
#   Debug Professor until it passes honestly.
#
# If this gate PASSES:
#   Record the commit hash in tests/regression/test_phase3_regression.py header.
#   Write and freeze that file.
#   Proceed to Phase 4.
#
# NEVER import this file as a pytest module — it has a main block and
# is designed to be run directly. pytest discovery is disabled by the
# function naming convention (no test_ prefix on top-level functions).

import os
import sys
import json
import time
import subprocess
import traceback
from datetime import datetime
from pathlib import Path

# Add project root to sys.path so core can be imported
sys.path.insert(0, str(Path(__file__).parent.parent))


# ── Constants ────────────────────────────────────────────────────────────────

COMPETITION_ID      = "spaceship-titanic"
TARGET_COLUMN       = "Transported"
ID_COLUMN           = "PassengerId"
EVALUATION_METRIC   = "accuracy"

# Gate threshold: top 40% = percentile >= 60
# Spaceship Titanic top-40% boundary ≈ 0.795 accuracy
TOP_40_PERCENT_THRESHOLD = 0.795

# Approximate LB percentile curve (accuracy → percentile, higher=better)
# Derived from competition LB at close.
LB_CURVE = [
    (0.770, 5.0),
    (0.785, 20.0),
    (0.795, 40.0),   # ← gate threshold
    (0.803, 60.0),
    (0.810, 80.0),
    (0.815, 90.0),
    (0.820, 95.0),
    (0.825, 99.0),
]

RESULTS_DIR = Path("tests/phase3_gate_results")
SESSION_ID  = f"phase3_gate_{int(time.time())}"


# ── Utilities ────────────────────────────────────────────────────────────────

def _load_env():
    """Load .env into os.environ if present."""
    env_path = Path(".env")
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


def _score_to_percentile(score: float) -> float:
    import numpy as np
    scores = [b[0] for b in LB_CURVE]
    pcts   = [b[1] for b in LB_CURVE]
    return float(np.interp(score, scores, pcts))


def _medal(percentile: float) -> str:
    if percentile >= 97: return "Gold"
    if percentile >= 90: return "Silver"
    if percentile >= 80: return "Bronze"
    return "None"


def _require_kaggle_credentials():
    username = os.getenv("KAGGLE_USERNAME", "")
    api_key  = os.getenv("KAGGLE_KEY", "")
    if not username or not api_key:
        print(
            "\nFATAL: KAGGLE_USERNAME and KAGGLE_KEY must be set in .env.\n"
            "Get your API key at: https://www.kaggle.com/settings/account\n"
        )
        sys.exit(1)


# ── Step 1: Run Professor ────────────────────────────────────────────────────

def step1_run_professor(data_dir: Path, result_dir: Path) -> dict:
    """
    Runs the full Professor pipeline on Spaceship Titanic.
    Returns the final state dict.
    Raises on pipeline error so the gate fails loudly.
    """
    print("\n[1/4] Running Professor pipeline on Spaceship Titanic...")

    train_path = data_dir / "train.csv"
    test_path  = data_dir / "test.csv"

    if not train_path.exists():
        raise FileNotFoundError(
            f"Training data not found at {train_path}.\n"
            "Run: kaggle competitions download -c spaceship-titanic -p "
            f"{data_dir} --unzip"
        )

    from core.state import initial_state
    
    state = initial_state(
        competition=COMPETITION_ID,
        data_path=str(train_path),
    )
    
    # Override standard variables for the local path and gate constraints
    state.update({
        "session_id":                 SESSION_ID,
        "train_path":                 str(train_path),
        "test_path":                  str(test_path),
        "raw_data_path":              str(train_path),  # Add raw_data_path explicitly
        "target_column":              TARGET_COLUMN,
        "id_column":                  ID_COLUMN,
        "evaluation_metric":          EVALUATION_METRIC,
        "task_type":                  "binary_classification",
        "budget_limit_usd":           10.0,
        "budget_remaining_usd":       10.0,
        "dag_version":                1,
        "external_data_allowed":      False,
        "hitl_required":              False,
        "replan_requested":           False,
        "critic_severity":            "unchecked",
        "model_registry":             {},
        "features_dropped":           [],
        "feature_order":              [],
        "current_node_failure_count": 0,
    })

    from agents import ml_optimizer
    ml_optimizer.N_OPTUNA_TRIALS = 20

    from core.professor import run_professor
    t_start     = time.time()
    final_state = run_professor(state)
    elapsed     = time.time() - t_start

    print(f"    Pipeline complete in {elapsed:.0f}s")
    print(f"    CV score:           {final_state.get('cv_mean', 'N/A')}")
    print(f"    Winning model:      {final_state.get('winning_model_type', 'N/A')}")
    print(f"    Features (final):   {final_state.get('n_features_final', 'N/A')}")

    return final_state


# ── Step 2: Prepare submission ───────────────────────────────────────────────

def step2_prepare_submission(final_state: dict, result_dir: Path) -> Path:
    """
    Locates or builds the submission.csv.
    Returns the path to a valid submission file.
    """
    print("\n[2/4] Preparing submission file...")

    # Check outputs directory first
    outputs_sub = Path(f"outputs/{SESSION_ID}/submission.csv")
    if outputs_sub.exists():
        print(f"    Found submission at {outputs_sub}")
        return outputs_sub

    # Check state
    if "submission_df" in final_state:
        import polars as pl
        sub_path = result_dir / "submission.csv"
        final_state["submission_df"].write_csv(sub_path)
        print(f"    Written submission from state to {sub_path}")
        return sub_path

    raise FileNotFoundError(
        "No submission.csv found.\n"
        f"Expected: outputs/{SESSION_ID}/submission.csv\n"
        "Check that submission_strategist wrote the file correctly."
    )


# ── Step 3: Submit to Kaggle ─────────────────────────────────────────────────

def step3_submit_to_kaggle(submission_path: Path) -> dict:
    """
    Submits to Kaggle via CLI and returns submission metadata.
    Polls until the submission is scored or times out (5 minutes).
    """
    print("\n[3/4] Submitting to Kaggle...")

    message = f"Professor Agent Phase 3 Gate — {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC"

    result = subprocess.run(
        [
            "kaggle", "competitions", "submit",
            "-c", COMPETITION_ID,
            "-f", str(submission_path),
            "-m", message,
        ],
        capture_output=True, text=True, shell=True
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Kaggle submission failed:\n{result.stderr}\n"
            "Common causes:\n"
            "  - Competition rules not accepted on kaggle.com\n"
            "  - submission.csv has wrong column names or format\n"
            "  - KAGGLE_USERNAME / KAGGLE_KEY not set correctly"
        )

    print(f"    Submission accepted: {result.stdout.strip()}")

    # Poll for score
    print("    Polling for score (timeout: 5 minutes)...")
    public_score = _poll_for_score(timeout_seconds=300)

    if public_score is None:
        raise TimeoutError(
            "Kaggle did not return a score within 5 minutes.\n"
            "Check the Kaggle submission history manually:\n"
            f"https://www.kaggle.com/competitions/{COMPETITION_ID}/submissions"
        )

    print(f"    Public LB score:    {public_score}")
    return {"public_score": public_score, "message": message}


def _poll_for_score(timeout_seconds: int = 300) -> float | None:
    """
    Polls Kaggle submissions list for the most recent submission's score.
    Returns the public score, or None on timeout.
    """
    deadline = time.time() + timeout_seconds
    poll_interval = 15  # seconds between polls

    while time.time() < deadline:
        result = subprocess.run(
            [
                "kaggle", "competitions", "submissions",
                "-c", COMPETITION_ID,
                "--csv",
            ],
            capture_output=True, text=True, shell=True
        )

        if result.returncode == 0 and result.stdout:
            lines = result.stdout.strip().splitlines()
            # CSV format: fileName,date,description,status,publicScore,privateScore
            if len(lines) >= 2:
                latest = lines[1].split(",")
                status = latest[3].strip() if len(latest) > 3 else ""
                if status.lower() == "complete" and len(latest) > 4:
                    score_str = latest[4].strip()
                    if score_str and score_str != "None":
                        try:
                            return float(score_str)
                        except ValueError:
                            pass

        remaining = int(deadline - time.time())
        if remaining > 0:
            print(f"    Score pending... ({remaining}s remaining)")
            time.sleep(poll_interval)

    return None


# ── Step 4: Assert gate ──────────────────────────────────────────────────────

def step4_assert_gate(
    final_state: dict,
    public_score: float,
    result_dir: Path,
) -> dict:
    """
    Asserts the gate condition and writes the gate result JSON.
    Returns the gate result dict.
    DOES NOT call sys.exit — caller handles that so we can always write the result file.
    """
    print("\n[4/4] Checking gate condition...")

    percentile  = _score_to_percentile(public_score)
    medal       = _medal(percentile)
    cv_score    = final_state.get("cv_mean")
    cv_gap      = round(abs(cv_score - public_score), 6) if cv_score else None

    gate_passed = public_score >= TOP_40_PERCENT_THRESHOLD
    gap_to_gate = round(public_score - TOP_40_PERCENT_THRESHOLD, 5)

    gate_result = {
        "gate_passed":            gate_passed,
        "public_score":           public_score,
        "gate_threshold":         TOP_40_PERCENT_THRESHOLD,
        "gap_to_gate":            gap_to_gate,
        "simulated_percentile":   round(percentile, 1),
        "simulated_medal":        medal,
        "cv_score":               cv_score,
        "cv_lb_gap":              cv_gap,
        "winning_model_type":     final_state.get("winning_model_type"),
        "n_features_final":       final_state.get("n_features_final"),
        "stability_score":        _best_stability_score(final_state),
        "n_pseudo_label_iterations": final_state.get("pseudo_label_iterations", 0),
        "critic_severity":        final_state.get("critic_severity", "unknown"),
        "session_id":             SESSION_ID,
        "competition_id":         COMPETITION_ID,
        "run_timestamp":          datetime.utcnow().isoformat(),
    }

    # Write result before asserting (so we have the file even if gate fails)
    result_path = result_dir / "gate_result.json"
    result_path.write_text(json.dumps(gate_result, indent=2))

    # Print summary
    print(f"\n{'='*60}")
    print(f"PHASE 3 GATE RESULT")
    print(f"{'='*60}")
    print(f"  Public LB score:      {public_score}")
    print(f"  Gate threshold (40%): {TOP_40_PERCENT_THRESHOLD}")
    print(f"  Gap to threshold:     {gap_to_gate:+.5f}")
    print(f"  Simulated percentile: {percentile:.1f}%")
    print(f"  Simulated medal:      {medal}")
    print(f"  CV score:             {cv_score}")
    print(f"  CV/LB gap:            {cv_gap}")
    print(f"  GATE:                 {'PASSED' if gate_passed else 'FAILED'}")
    print(f"{'='*60}")

    if gate_passed:
        print(
            "\nPHASE 3 GATE PASSED.\n"
            "\nNext steps:\n"
            "  1. git rev-parse HEAD  (record this commit hash)\n"
            "  2. Write tests/regression/test_phase3_regression.py\n"
            "     (include the commit hash in the file header)\n"
            "  3. Proceed to Phase 4.\n"
        )
    else:
        print(
            f"\nPHASE 3 GATE FAILED.\n"
            f"  Score {public_score:.5f} is {abs(gap_to_gate):.5f} below the top-40% threshold "
            f"({TOP_40_PERCENT_THRESHOLD}).\n"
            f"\nDo NOT proceed to Phase 4.\n"
            f"Debug Professor using the gate_result.json at:\n"
            f"  {result_path}\n"
            f"\nCommon causes:\n"
            f"  cv_lb_gap > 0.005 → leakage or validation fold contamination\n"
            f"  winning_model=catboost on first run → Optuna search space too wide\n"
            f"  n_features_final < 10 → null importance filter over-aggressive\n"
            f"  n_features_final > 50 → null importance filter not running\n"
        )

    return gate_result


def _best_stability_score(state: dict) -> float | None:
    registry = state.get("model_registry", {})
    if not registry:
        return None
    scores = [e.get("stability_score") for e in registry.values() if e.get("stability_score")]
    return round(max(scores), 6) if scores else None


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    _load_env()
    _require_kaggle_credentials()

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    result_dir = RESULTS_DIR / SESSION_ID
    result_dir.mkdir(parents=True, exist_ok=True)

    data_dir = Path("tests/harness/data") / COMPETITION_ID / "raw"

    print(f"{'='*60}")
    print(f"PROFESSOR AGENT — PHASE 3 GATE")
    print(f"Competition: {COMPETITION_ID}")
    print(f"Requirement: top 40% (score >= {TOP_40_PERCENT_THRESHOLD})")
    print(f"Session: {SESSION_ID}")
    print(f"{'='*60}")

    exit_code = 1

    try:
        final_state      = step1_run_professor(data_dir, result_dir)
        submission_path  = step2_prepare_submission(final_state, result_dir)
        submission_result = step3_submit_to_kaggle(submission_path)
        gate_result      = step4_assert_gate(
            final_state,
            submission_result["public_score"],
            result_dir,
        )
        exit_code = 0 if gate_result["gate_passed"] else 1

    except KeyboardInterrupt:
        print("\nGate run interrupted by user.")
    except Exception as e:
        print(f"\nFATAL ERROR during gate run: {type(e).__name__}: {e}")
        traceback.print_exc()
        # Write an error result so we have a record
        error_result = {
            "gate_passed":   False,
            "error":         f"{type(e).__name__}: {str(e)[:500]}",
            "session_id":    SESSION_ID,
            "run_timestamp": datetime.utcnow().isoformat(),
        }
        (result_dir / "gate_result.json").write_text(json.dumps(error_result, indent=2))

    sys.exit(exit_code)


if __name__ == "__main__":
    main()