"""
Hackathon Publisher — assembles all required deliverables.

Unlike the traditional publisher which produces submission.csv + notebook + writeup,
the hackathon publisher produces whatever the competition rubric requires:
- Kaggle Notebook (.ipynb format for hackathons, not .py)
- Project Writeup (already generated by Narrative Engine)
- Cover Image (auto-generated from the key finding visualization)
- Project Link README (for GitHub)
- requirements.txt
"""

import os
import json
import shutil
from datetime import datetime
from core.state import ProfessorState
from tools.operator_channel import emit_to_operator
from tools.code_ledger import get_kept_entries, get_reasoning_chain
from shields.submission_safety import verify_submission, backup_submission


def hackathon_publisher(state: ProfessorState) -> dict:
    """
    Final hackathon pipeline node. Produces all required deliverables.
    
    Reads: EVERYTHING — needs full state for notebook + writeup + verification
    Writes: solution_notebook_path, solution_writeup_path, code_ledger_path,
            notebook_reproduction_validated
    Emits: RESULT (Milestone — final summary), GATE (GUIDED mode: submit?)
    """
    session_dir = f"outputs/{state.session_id}"
    os.makedirs(session_dir, exist_ok=True)
    
    rubric = state.hackathon_rubric or {}
    requirements = rubric.get("submission_requirements", ["notebook", "writeup"])
    
    deliverables = {}
    errors = []
    
    emit_to_operator("📦 Assembling hackathon deliverables...", level="STATUS")
    
    # ═══════════════════════════════════════
    # 1. NOTEBOOK (always required)
    # ═══════════════════════════════════════
    if "notebook" in requirements:
        try:
            notebook_path = _assemble_hackathon_notebook(state, session_dir)
            deliverables["notebook"] = notebook_path
            emit_to_operator(f"✅ Notebook generated: {notebook_path}", level="STATUS")
        except Exception as e:
            errors.append(f"Notebook generation failed: {str(e)[:200]}")
            emit_to_operator(f"❌ Notebook generation failed: {str(e)[:100]}", level="STATUS")
    
    # ═══════════════════════════════════════
    # 2. WRITEUP (already generated by Narrative Engine)
    # ═══════════════════════════════════════
    if "writeup" in requirements:
        writeup_path = state.hackathon_writeup_path
        if writeup_path and os.path.exists(writeup_path):
            deliverables["writeup"] = writeup_path
            # Handle absence of hackathon_writeup_word_count safely
            word_count = getattr(state, "hackathon_writeup_word_count", 0)
            emit_to_operator(f"✅ Writeup ready: {writeup_path} ({word_count} words)", level="STATUS")
        else:
            errors.append("Writeup not generated by Narrative Engine")
            emit_to_operator("❌ Writeup missing — Narrative Engine may have failed", level="STATUS")
    
    # ═══════════════════════════════════════
    # 3. COVER IMAGE (if required)
    # ═══════════════════════════════════════
    if "cover_image" in requirements:
        try:
            cover_path = _generate_cover_image(state, session_dir)
            deliverables["cover_image"] = cover_path
            emit_to_operator(f"✅ Cover image generated: {cover_path}", level="STATUS")
        except Exception as e:
            errors.append(f"Cover image failed: {str(e)[:200]}")
            emit_to_operator(f"⚠️ Cover image failed — use a narrative plot as cover", level="STATUS")
    
    # ═══════════════════════════════════════
    # 4. PROJECT LINK / README (if required)
    # ═══════════════════════════════════════
    if "project_link" in requirements:
        try:
            readme_path = _generate_github_readme(state, session_dir)
            deliverables["readme"] = readme_path
            emit_to_operator(
                f"✅ README.md generated for GitHub repo\n"
                f"⚠️ You need to: create a GitHub repo, push the code, paste the URL into the submission",
                level="STATUS"
            )
        except Exception as e:
            errors.append(f"README failed: {str(e)[:200]}")
    
    # ═══════════════════════════════════════
    # 5. REQUIREMENTS.TXT (always)
    # ═══════════════════════════════════════
    try:
        req_path = _generate_requirements(deliverables.get("notebook", ""), session_dir)
        deliverables["requirements"] = req_path
    except Exception:
        pass  # Non-critical
    
    # ═══════════════════════════════════════
    # 6. SUBMISSION VERIFICATION (if there's a submission.csv)
    # ═══════════════════════════════════════
    submission_path = state.submission_path or os.path.join(session_dir, "submission.csv")
    if os.path.exists(submission_path):
        verification = verify_submission(
            submission_path=submission_path,
            sample_submission_path=state.preflight_submission_format.get("path", ""),
            canonical_test_rows=state.canonical_test_rows,
        )
        if verification["valid"]:
            backup_submission(submission_path, session_dir)
            deliverables["submission"] = submission_path
        else:
            errors.append(f"Submission verification failed: {verification['issues']}")
    
    # ═══════════════════════════════════════
    # 7. CODE LEDGER (always — provenance)
    # ═══════════════════════════════════════
    ledger_path = os.path.join(session_dir, "code_ledger.jsonl")
    if os.path.exists(ledger_path):
        deliverables["code_ledger"] = ledger_path
    
    # ═══════════════════════════════════════
    # 8. COST REPORT
    # ═══════════════════════════════════════
    cost_data = state.get("cost_tracker") or {}
    total_calls = cost_data.get("llm_calls", 0)
    total_cost_usd = cost_data.get("api_cost_usd", 0.0)
    
    # ═══════════════════════════════════════
    # FINAL MILESTONE — Present everything to operator
    # ═══════════════════════════════════════
    
    thesis_statement = (state.active_thesis or {}).get("statement", "No thesis selected")
    
    deliverable_list = "\n".join([
        f"  {'✅' if k in deliverables else '❌'} {k}: {deliverables.get(k, 'MISSING')}"
        for k in requirements + ["requirements", "code_ledger"]
    ])
    
    error_list = ""
    if errors:
        error_list = "\n⚠️ Issues:\n" + "\n".join(f"  - {e}" for e in errors)
    
    word_count = getattr(state, "hackathon_writeup_word_count", 0)
    
    final_msg = f"""🏆 HACKATHON SUBMISSION READY

📋 Thesis: "{thesis_statement[:100]}"

🎯 Model: {state.best_model_type or 'N/A'} — CV: {state.cv_mean or 0:.4f}
📊 Features: {len(state.feature_manifest or [])} ({len(state.thesis_effect_sizes or {})} with measured effects)
🎨 Plots: {len([p for p in (state.narrative_plots or []) if p.get('path')])} generated
📝 Writeup: {word_count} words

📦 Deliverables:
{deliverable_list}
{error_list}

💰 Cost: {total_calls} LLM calls, ${total_cost_usd:.2f}

Next steps:
1. Review the writeup at {deliverables.get('writeup', 'N/A')}
2. Review the notebook at {deliverables.get('notebook', 'N/A')}
3. Upload to Kaggle: notebook → writeup → cover image → project link
"""
    
    # In GUIDED mode: require operator approval before marking as final
    if getattr(state, "hitl_mode", "") == "guided":
        response = emit_to_operator(final_msg + "\nReply /submit to finalize or /iterate to revise", level="GATE")
    else:
        emit_to_operator(final_msg, level="RESULT")
    
    return {
        "solution_notebook_path": deliverables.get("notebook", ""),
        "solution_writeup_path": deliverables.get("writeup", ""),
        "code_ledger_path": deliverables.get("code_ledger", ""),
        "notebook_reproduction_validated": False,  # Hackathon notebooks are .ipynb — different validation
    }

def _assemble_hackathon_notebook(state: ProfessorState, session_dir: str) -> str:
    """
    Assemble a Kaggle-compatible .ipynb notebook.
    
    Unlike traditional solution_notebook.py:
    - Format is .ipynb (JSON structure with markdown + code cells)
    - Interleaves narrative markdown with executable code
    - The notebook IS part of the submission — judges read it
    - Must run end-to-end without errors
    """
    cells = []
    
    # ── Title + Introduction Cell (markdown) ──
    thesis = state.active_thesis or {}
    cells.append(_markdown_cell(
        f"# {thesis.get('statement', state.competition_name)}\n\n"
        f"**Competition:** {state.competition_name}\n"
        f"**Approach:** {thesis.get('angle', 'Thesis-driven analysis')}\n"
        f"**Target Audience:** {thesis.get('target_audience', 'Practitioners')}\n\n"
        f"This notebook implements and validates our thesis through structured "
        f"data analysis, feature engineering, and model training."
    ))
    
    # ── Setup Cell (code) ──
    cells.append(_code_cell(
        "# Setup\n"
        "import polars as pl\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "from sklearn.model_selection import StratifiedKFold\n"
        "from sklearn.metrics import roc_auc_score\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "SEED = 42\n"
        "np.random.seed(SEED)\n"
        "sns.set_style('whitegrid')\n"
        "plt.rcParams['figure.figsize'] = (10, 6)\n"
        "plt.rcParams['font.size'] = 12"
    ))
    
    # ── Data Loading Section ──
    cells.append(_markdown_cell("## Data Loading & Exploration"))
    
    # Get kept code blocks from Code Ledger, grouped by agent
    kept_entries = get_kept_entries(session_dir)
    
    # Data Engineer code
    de_entries = [e for e in kept_entries if e["agent"] == "data_engineer" and e["success"]]
    for entry in de_entries:
        cells.append(_markdown_cell(f"### {entry['purpose']}"))
        cells.append(_code_cell(_clean_code(entry["code"])))
    
    # EDA code + narrative
    cells.append(_markdown_cell("## Exploratory Data Analysis"))
    eda_entries = [e for e in kept_entries if e["agent"] == "eda_agent" and e["success"]]
    for entry in eda_entries:
        cells.append(_code_cell(_clean_code(entry["code"])))
    
    # ── Thesis Statement ──
    cells.append(_markdown_cell(
        f"## Our Thesis\n\n"
        f"> **{thesis.get('statement', '')}**\n\n"
        f"**Hypothesis:** {thesis.get('hypothesis', '')}\n\n"
        f"**Condition:** We compare outcomes across `{thesis.get('condition_variable', '')}` "
        f"to test whether this factor creates systematic differences."
    ))
    
    # ── External Data Integration ──
    if getattr(state, "external_datasets", None):
        cells.append(_markdown_cell("## External Data Integration"))
        scout_entries = [e for e in kept_entries if e["agent"] == "external_data_scout" and e["success"]]
        for entry in scout_entries:
            cells.append(_markdown_cell(f"### {entry['purpose']}"))
            cells.append(_code_cell(_clean_code(entry["code"])))
    
    # ── Feature Engineering ──
    cells.append(_markdown_cell("## Hypothesis-Testing Feature Engineering"))
    ff_entries = [e for e in kept_entries if e["agent"] == "feature_factory" and e["success"]]
    for entry in ff_entries:
        cells.append(_markdown_cell(f"### Round {entry.get('round_num', '?')}: {entry['purpose']}"))
        cells.append(_code_cell(_clean_code(entry["code"])))
    
    # ── Results — Effect Sizes ──
    if getattr(state, "thesis_effect_sizes", None):
        cells.append(_markdown_cell("## Results: Testing the Thesis"))
        
        effect_summary = "| Feature | Effect Size | P-value | Direction |\n|---|---|---|---|\n"
        for fname, effect in state.thesis_effect_sizes.items():
            effect_summary += (
                f"| {fname} | {effect.get('effect_size', 'N/A'):.3f} "
                f"({effect.get('effect_magnitude', '?')}) | "
                f"{effect.get('p_value', 'N/A'):.4f} | "
                f"{effect.get('direction', '?')} |\n"
            )
        cells.append(_markdown_cell(effect_summary))
    
    # ── Model Training ──
    cells.append(_markdown_cell("## Model Training"))
    ml_entries = [e for e in kept_entries if e["agent"] == "ml_optimizer" and e["success"]]
    for entry in ml_entries:
        cells.append(_code_cell(_clean_code(entry["code"])))
    
    # ── Narrative Plots ──
    if getattr(state, "narrative_plots", None):
        cells.append(_markdown_cell("## Key Findings — Visualizations"))
        for plot in state.narrative_plots:
            if plot.get("path") and os.path.exists(plot["path"]):
                cells.append(_markdown_cell(f"### {plot.get('caption', 'Figure')}"))
                # Embed plot as inline image (copy to notebook output directory)
                plot_filename = os.path.basename(plot["path"])
                cells.append(_code_cell(
                    f"from IPython.display import Image, display\n"
                    f"display(Image(filename='{plot_filename}'))"
                ))
    
    # ── Conclusion ──
    cells.append(_markdown_cell(
        "## Conclusion\n\n"
        f"Our analysis {'supports' if getattr(state, 'thesis_effect_sizes', None) else 'explored'} "
        f"the thesis that {thesis.get('statement', 'N/A')}. "
        f"The key findings are documented in the project writeup."
    ))
    
    # ── Build .ipynb structure ──
    notebook = {
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5,
        "cells": cells,
    }
    
    notebook_path = os.path.join(session_dir, "hackathon_notebook.ipynb")
    with open(notebook_path, "w") as f:
        json.dump(notebook, f, indent=2)
    
    return notebook_path


def _markdown_cell(content: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [content],
    }


def _code_cell(content: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "source": [content],
        "outputs": [],
        "execution_count": None,
    }


def _clean_code(code: str) -> str:
    """Clean sandbox code for notebook inclusion."""
    import re
    lines = code.split("\n")
    cleaned = []
    skip_patterns = [
        "from tools.", "from agents.", "from shields.", "from graph.", "from core.",
        "emit_to_operator(", "run_in_sandbox(", "mark_rejected(",
        "__DIAGNOSTICS__", "# === USER CODE",
    ]
    for line in lines:
        if any(pat in line.strip() for pat in skip_patterns):
            continue
        # Replace absolute sandbox paths
        line = re.sub(r'["\'].*?/sandbox/.*?/([^/"\']+)["\']', r'"\1"', line)
        cleaned.append(line)
    return "\n".join(cleaned)


def _generate_cover_image(state: ProfessorState, session_dir: str) -> str:
    """
    Generate a cover image from the key finding visualization.
    Resizes the best narrative plot to competition dimensions.
    
    Triagegeist requires 560 x 280 px.
    """
    from tools.sandbox import run_in_sandbox
    
    # Find the best narrative plot (finding_summary or conditional_comparison)
    source_plot = None
    for plot in (state.narrative_plots or []):
        if plot.get("path") and os.path.exists(plot["path"]):
            if plot.get("plot_type") in ("finding_summary", "conditional_comparison"):
                source_plot = plot["path"]
                break
    
    if not source_plot:
        # Use the first available plot
        for plot in (state.narrative_plots or []):
            if plot.get("path") and os.path.exists(plot["path"]):
                source_plot = plot["path"]
                break
    
    if not source_plot:
        raise ValueError("No narrative plots available for cover image")
    
    # Resize to competition dimensions
    cover_path = os.path.join(session_dir, "cover_image.png")
    
    code = f"""
from PIL import Image

img = Image.open("{source_plot}")
# Crop to 2:1 aspect ratio (560x280)
width, height = img.size
target_ratio = 560 / 280  # 2:1
current_ratio = width / height

if current_ratio > target_ratio:
    # Too wide — crop sides
    new_width = int(height * target_ratio)
    left = (width - new_width) // 2
    img = img.crop((left, 0, left + new_width, height))
else:
    # Too tall — crop top/bottom
    new_height = int(width / target_ratio)
    top = (height - new_height) // 2
    img = img.crop((0, top, width, top + new_height))

img = img.resize((560, 280), Image.LANCZOS)
img.save("{cover_path}")
print(f"Cover image saved: {{img.size}}")
"""
    
    result = run_in_sandbox(code=code, agent_name="hackathon_publisher", purpose="Generate cover image")
    
    if result["success"] and os.path.exists(cover_path):
        return cover_path
    else:
        raise ValueError(f"Cover image generation failed: {result.get('stderr', '')[:200]}")


def _generate_github_readme(state: ProfessorState, session_dir: str) -> str:
    """Generate a README.md for the GitHub project link."""
    thesis = state.active_thesis or {}
    
    readme = f"""# {state.competition_name} — {thesis.get('statement', 'Analysis')[:80]}

## Overview
{thesis.get('angle', 'Thesis-driven analysis for hackathon competition.')}

## Thesis
> {thesis.get('statement', '')}

**Hypothesis:** {thesis.get('hypothesis', '')}

## Results
- **Model:** {state.best_model_type or 'N/A'}
- **CV Score:** {state.cv_mean or 0:.4f}
- **Key Effect Sizes:** {len(state.thesis_effect_sizes or {})} features with measured conditional effects

## Files
- `hackathon_notebook.ipynb` — Full analysis notebook (runs end-to-end)
- `hackathon_writeup.md` — Project writeup
- `requirements.txt` — Python dependencies
- `narrative_plots/` — Thesis-supporting visualizations

## Setup
```bash
pip install -r requirements.txt
jupyter notebook hackathon_notebook.ipynb
```

## Data Sources
"""
    
    # Add data citations
    for ds in (getattr(state, "external_datasets", None) or []):
        readme += f"- **{ds.get('name', '?')}**: {ds.get('source_url', 'URL not available')}\n"
    
    recommended = (state.hackathon_rubric or {}).get("recommended_datasets", [])
    for ds in recommended:
        readme += f"- **{ds.get('name', '?')}**: {ds.get('url', '')}\n"
    
    readme += f"\n## License\nThis project was created for {state.competition_name}.\n"
    
    readme_path = os.path.join(session_dir, "README.md")
    with open(readme_path, "w") as f:
        f.write(readme)
    
    return readme_path


def _generate_requirements(notebook_path: str, session_dir: str) -> str:
    """Generate requirements.txt from notebook imports."""
    from tools.solution_assembler import generate_requirements
    return generate_requirements(notebook_path, session_dir)
