# tools/solution_assembler.py

import os
import json
import logging
import polars as pl
from pathlib import Path
from datetime import datetime, timezone
from typing import List, Dict, Any, Tuple

from tools.code_ledger import CodeLedgerEntry
from tools.llm_provider import llm_call, _safe_json_loads
from tools.sandbox import run_in_sandbox

logger = logging.getLogger(__name__)

# ── standalone script template ──────────────────────────────────────────────

STANDALONE_TEMPLATE = """# Standalone ML Solution - Generated by Professor v2.0
# Date: {timestamp}
# Target: {target_col}

import os
import sys
import polars as pl
import numpy as np
import lightgbm as lgb
import xgboost as xgb
import catboost
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.preprocessing import *

# --- 1. CONFIGURATION ---
TRAIN_PATH = "{train_path}"
TEST_PATH = "{test_path}"
TARGET_COL = "{target_col}"

# --- 2. DATA LOADING ---
print("Loading data...")
train = pl.read_parquet(TRAIN_PATH) if TRAIN_PATH.endswith(".parquet") else pl.read_csv(TRAIN_PATH)
test = pl.read_parquet(TEST_PATH) if TEST_PATH.endswith(".parquet") else pl.read_csv(TEST_PATH)

# We use 'df' as the variable name for compatibility with generated blocks
df = train

# --- 3. PIPELINE BLOCKS ---
{code_blocks}

# --- 4. FINAL OUTPUT ---
# (Assumes last block produced submission.csv or updated df_test)
print("Solution execution complete.")
"""

# ── Core Logic ──────────────────────────────────────────────────────────────

def assemble_standalone_solution(
    session_id: str,
    winning_sequence: List[CodeLedgerEntry],
    train_path: str,
    test_path: str,
    target_col: str
) -> Dict[str, str]:
    """
    Compiles ledger entries into a standalone .py script and narrative .md.
    """
    output_dir = Path(f"outputs/{session_id}/solution")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Compile Code
    code_blocks = []
    for entry in winning_sequence:
        code_blocks.append(f"\n# --- Agent: {entry.agent} ({entry.purpose}) ---")
        code_blocks.append(entry.code)
        
    full_script = STANDALONE_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).isoformat(),
        train_path=train_path,
        test_path=test_path,
        target_col=target_col,
        code_blocks="\n".join(code_blocks)
    )
    
    script_path = output_dir / "solution_notebook.py"
    with open(script_path, "w") as f:
        f.write(full_script)

    # 2. Generate Narrative Write-up
    writeup_prompt = f"""Generate a high-level summary of the winning machine learning pipeline.
PIPELINE COMPONENTS:
"""
    for entry in winning_sequence:
        writeup_prompt += f"- {entry.agent}: {entry.purpose} (Reasoning: {entry.llm_reasoning})\n"
        
    writeup_prompt += "\nProvide a structured Markdown write-up including: Approach, Key Features, and Model Selection."
    
    try:
        writeup = llm_call(writeup_prompt)
    except:
        writeup = "# Solution Write-up\nSummary generation failed. Check code ledger for details."
        
    writeup_path = output_dir / "solution_writeup.md"
    with open(writeup_path, "w") as f:
        f.write(writeup)

    # 3. Generate requirements.txt
    reqs = ["polars", "numpy", "lightgbm", "scikit-learn", "xgboost", "catboost", "scipy"]
    reqs_path = output_dir / "requirements.txt"
    with open(reqs_path, "w") as f:
        f.write("\n".join(reqs))

    return {
        "script": str(script_path),
        "writeup": str(writeup_path),
        "requirements": str(reqs_path)
    }

def verify_reproduction(script_code: str, session_id: str) -> Dict[str, Any]:
    """
    Validates that the generated script runs without professor dependencies.
    """
    # Use sandbox but with STANDALONE purpose
    res = run_in_sandbox(
        script_code,
        agent_name="solution_assembler",
        purpose="Reproduction check",
        working_dir=f"outputs/{session_id}/solution"
    )
    return res
